### ISSUE TITLE
GetNextOccurence_s_?

### ISSUE THREAD

**Issue by unionthugface** [HangfireIO/Cronos#1]
Hi guys, I'm using NCronTab right now because it has a `GetNextOccurence*s*` method that returns an `IEnumerable<T>` of `DateTime`'s when you give it a date range.  Is there a good way to get the same result from your library?  Thanks!

**Comment by aidmsu** [comment]
Hi, @unionthugface!

We tried to make Cronos API as simple as possible. Thus we decided not to complicate API by lots of methods. If you need `GetNextOccurences` method you can implement it as extension method:

```csharp
public static IEnumerable<DateTime> GetNextOccurrences(
	this CronExpression expression, 
	DateTime from, 
	DateTime to, 
	bool inclusive = false)
{
    for (var occurrence = expression.GetNextOccurrence(from, inclusive);
        occurrence < to || occurrence == to && inclusive;
        occurrence = expression.GetNextOccurrence(occurrence.Value))
    {
        yield return occurrence.Value;
    }
}
```

**Comment by aidmsu** [comment]
@unionthugface , more details about why we don't add `GetNextOccurrences`:

If we add this method we have to add `to` parameter: 

```csharp
public IEnumerable<DateTime> GetNextOccurrences(DateTime from, DateTime to);
``` 
The question arises: are `from` and `to` *inclusive* or *exclusive*? To eliminate indetermination let's add `inclusive` parameter:

```csharp
public IEnumerable<DateTime> GetNextOccurrences(DateTime from, DateTime to, bool inclusive);
``` 
Indeed the indetermination hasn't disappeared: does `inclusive` affect `from`, `to` or both? We can add `fromInclusive` and `toInclusive` but it's too cumbersome.

Thus we decided to leave only `GetNextOccurrence(DateTime from, bool inclusive = false)` method.

**Comment by unionthugface** [comment]
Thanks for the response @aidmsu !

**Comment by aidmsu** [comment]
Hi @unionthugface!

We thought a lot about Cronos API. Finally we added the following method:

```csharp
IEnumerable<DateTime> GetOccurrences(
    DateTime fromUtc, 
    DateTime toUtc, 
    bool fromInclusive = true,
    bool toInclusive = false);
```

Thus you have an opportunity to get occurences in given date range :smile:

**Comment by unionthugface** [comment]
Wuuuuut!!  You guys are awesome.  I'm grateful and humbled you took the time to respond to me.  Thanks so much!
