### ISSUE TITLE
Feature request: CronExpression description

### ISSUE THREAD

**Issue by cocowalla** [HangfireIO/Cronos#14]
This is a feature request for a new method on `CronExpression` that provides a human-readable description of the cron expression.

For example `30 12 LW * *` would show `12:30 on the last weekday of the month`

**Comment by aidmsu** [comment]
Hello!

Thank you for your interest in Cronos.

Converting cron expressions into human readable descriptions is difficult to implement feature. If we do it we will have to support different languages, not only English. I'm not sure that it should be in this repo.

Moreover, there is a popular project [cron-expression-descriptor](https://github.com/bradymholt/cron-expression-descriptor) that have provides this feature. May be you should see it.

**Comment by cocowalla** [comment]
I'm already using cron-expression-descriptor, but thought it would be nice to lose a dependency and thought cron descriptions were cohesive enough to include in this library. But l hadnt considered the multi-language aspect, and on reflection I agree!
