### ISSUE TITLE
Can we use this when scheduling recurring hangfire jobs?

### ISSUE THREAD

**Issue by markalanevans** [HangfireIO/Cronos#19]
We use hangfire pro and i'd like to have jobs run on the last sunday for first sunday of every month. Is that possible?

**Comment by odinserj** [comment]
Hangfire uses this library since version 1.7.0, so you can use `0 0 ? * 7L` for last Sunday of every month or `0 0 ? * 7#1` for the first Sunday in that version.

**Comment by markalanevans** [comment]
Perfect! Thank you!

**Comment by markalanevans** [comment]
@odinserj can you not use commas when using the # .  For ex i'd like jobs ran on the 1st & 3rd Wed.
