### ISSUE TITLE
The documentation for GetOccurences is wrong.

### ISSUE THREAD

**Issue by nickduch** [HangfireIO/Cronos#28]
In the README, at this paragraph:
https://github.com/HangfireIO/Cronos/blob/master/README.md#getting-occurrences-within-a-range.

The return type should be `IEnumerable<DateTime>` instead of `DateTime?`.
`
IEnumerable<DateTime> occurrences = expression.GetOccurrences(
    DateTime.UtcNow,
    DateTime.UtcNow.AddYears(1),
    fromInclusive: true,
    toInclusive: false);
`

**Comment by odinserj** [comment]
Thanks, was already fixed!
