### ISSUE TITLE
Support for F (First) in non-standard characters

### ISSUE THREAD

**Issue by Cynicszm** [HangfireIO/Cronos#31]
Hi,

The documentation lists support for non-standard characters like L, W, # and their combinations.

Could F (First) be added?

Thanks

**Comment by odinserj** [comment]
Could you tell me where you see the `F` symbol in action, e.g. in what project? It is possible to specify first weekday via the the following expression: `0 0 1W * *`, also for example third weekday gives the `0 0 3W * *` expression. I've checked [Wikipedia](https://en.wikipedia.org/wiki/Cron#Non-standard_characters) and original [Quartz documentation](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html#special-characters), but unfortunately found nothing about the `F` character.

**Comment by Cynicszm** [comment]
Thank you it looks like it was added as a custom extension and we should be using the expressions above. 

Appreciate the quick response.
