### ISSUE TITLE
Support for different calendars

### ISSUE THREAD

**Issue by ghominejad** [HangfireIO/Cronos#32]
It seems Cronos only supports Gregorian calendar, Do you have any workaround to use different calendars with Cronos?

Is supporting for other calendars in you future plans?

**Comment by odinserj** [comment]
Yes, only Gregorian is supported. Do you have any examples of Cron parsers which support other calendars?

**Comment by ghominejad** [comment]
No but maybe I could help to implement it. 

I saw you've implemented calendar specific things inside the `CalendarHelper` class while `.Net` has already implemented `GregorianCalendar`.

Is this because of performance reasons?
