### ISSUE TITLE
0 0 1 8 0 can not be parsed

### ISSUE THREAD

**Issue by paul-cheung** [HangfireIO/Cronos#35]
Frankly, the "0 0 1 8 0" was a well-formed value, It indicates "At 00:00 on day-of-month 1 and on Sunday in August".
but it can not be parsed on version 0.7.0
Any latest implementation of this project?

**Comment by aodpi** [comment]
I've just tried it and it seems to parse just fine. I did it on a .net 5.0 console app project.
