### ISSUE TITLE
Does not accept cron expression

### ISSUE THREAD

**Issue by qudooschaudhry** [HangfireIO/Cronos#38]
Is this not a valid cron expression? 

`0 0 11 * 7 SAT`

Cronos fails with : 'Unexpected character 'S'.'

**Comment by qudooschaudhry** [comment]
doesn't take this either 

`0 0 11 * 7 6`

**Comment by odinserj** [comment]
Please specify `CronFormat.IncludeSeconds` in the constructor, otherwise it's unclear in general case whether 6th part is about seconds or about years.

```csharp
var expression = CronExpression.Parse("0 0 11 * 7 SAT", CronFormat.IncludeSeconds);
Console.WriteLine(expression.GetNextOccurrence(DateTime.UtcNow));
```

**Comment by qudooschaudhry** [comment]
Thank you that was it.

**Comment by jbennink** [comment]
**PLEASE CLOSE ME**
