### ISSUE TITLE
Is hangfire support second ?

### ISSUE THREAD

**Issue by a764578566** [HangfireIO/Cronos#4]
`            RecurringJob.AddOrUpdate(
                 () => Console.WriteLine("Recurring!"),
                 "* * * * * *", queue: "test");
`
![image](https://user-images.githubusercontent.com/14343051/29961326-e4f8e876-8f31-11e7-8fd5-675bf15ac92d.png)

but in HangfireIO/Cronos's README.md

                                       Allowed values    Allowed special characters   Comment

┌───────────── second (optional)       0-59              * , - /                      
│ ┌───────────── minute                0-59              * , - /                      
│ │ ┌───────────── hour                0-23              * , - /                      
│ │ │ ┌───────────── day of month      1-31              * , - / L W ?                
│ │ │ │ ┌───────────── month           1-12 or JAN-DEC   * , - /                      
│ │ │ │ │ ┌───────────── day of week   0-6  or SUN-SAT   * , - / # L ?                Both 0 and 7 means SUN
│ │ │ │ │ │
* * * * * *

**Comment by odinserj** [comment]
Hangfire doesn't use Cronos yet, the upcoming 1.7.0 release will do, and I have an idea of how to allow second-based intervals. I'll close this issue, because this repository is not for Hangfire.

**Comment by MNF** [comment]
Related Hangfire issue https://github.com/HangfireIO/Hangfire/issues/167. is still opened (sinc 2014)
