### ISSUE TITLE
0 0/3 * 1/1 * ? cannot be parsed

### ISSUE THREAD

**Issue by AlexandruIstrate** [HangfireIO/Cronos#40]
I tried using the `0 0/3 * 1/1 * ?` Cron expression but it tells me the `?` character is unexpected.

I don't understand why it has issues parsing this since I've been using it with `Quartz.Net` and it works fine.

What is the problem?

Thanks

**Comment by odinserj** [comment]
Please specify `CronFormat.IncludeSeconds` in the constructor, otherwise it's unclear in general case whether 6th part is about seconds or about years.

```csharp
var expression = CronExpression.Parse("0 0/3 * 1/1 * ?", CronFormat.IncludeSeconds);
Console.WriteLine(expression.GetNextOccurrence(DateTime.UtcNow));
```

**Comment by AlexandruIstrate** [comment]
Yeah, that makes sense. I did notice my format being different.
