### ISSUE TITLE
Missing a date over fall DST

### ISSUE THREAD

**Issue by thegrima** [HangfireIO/Cronos#5]
Hi,

I'm having an issues with Cronos v0.6.2 when trying to generates a list of occurrences across last daylight saving change.

Here is a simple code to reproduce. It try to generate each 1/4h from 00:00 utc to 03:00 utc the night of dst for the Western Europe timezone.

            var tzi = TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time");
            var begin = new DateTime(2017, 10, 29, 00, 00, 00, DateTimeKind.Utc);
            var end = new DateTime(2017, 10, 29, 03, 00, 00, DateTimeKind.Utc);
            var expr = CronExpression.Parse("0/15 * * * *");

            var dates = expr.GetOccurrences(begin, end, tzi);

            foreach (var d in dates)
            {
                Console.WriteLine(d);
            }

            Console.ReadKey();

Result is :

> 29-10-17 01:00:00
> 29-10-17 01:15:00
> 29-10-17 01:30:00
> 29-10-17 01:45:00
> 29-10-17 02:15:00
> 29-10-17 02:30:00
> 29-10-17 02:45:00

Unless I missed something, expected result would be :

> 29-10-17 01:00:00
> 29-10-17 01:15:00
> 29-10-17 01:30:00
> 29-10-17 01:45:00
> **29-10-17 02:00:00**
> 29-10-17 02:15:00
> 29-10-17 02:30:00
> 29-10-17 02:45:00

**Comment by odinserj** [comment]
This is definitely a bug, thanks for reporting! Moreover, this snippet hangs on .NET Core, looping again and again. @aidmsu, could you check this?

**Comment by thegrima** [comment]
The proposed fix was tested with .Net 4.6.1 (so not with .net core)

**Comment by thegrima** [comment]
Works for me, thanks.
Any plan for a 0.6.3 ?

**Comment by odinserj** [comment]
Cronos 0.6.3 is already on NuGet, see https://www.nuget.org/packages/Cronos/0.6.3
