### ISSUE TITLE
invalid value for system.timers.timer 

### ISSUE THREAD

**Issue by arun069** [HangfireIO/Cronos#50]
hi,
I am getting error when I am setting CronExpression  for month.

Error Message: Invalid value '2376995117.7807' for parameter 'interval'.'

// Cron setting 
  services.AddCronJob<WebhookTableJob>(c =>
            {
                c.TimeZoneInfo = TimeZoneInfo.Local;
                c.CronExpression = @"0 0 1 * *"; 
            });

when google for this issue I found that System.Timers.Timer only store maximum 25 day time value

**Comment by odinserj** [comment]
Please note that the Cronos package doesn't contain the `AddCronJob` method and doesn't have any integration with System.Timers.Timer class, so it comes from another library and this issues doesn't relate to Cronos.

**Comment by mattheys** [comment]
Looks like you are following this pattern https://github.com/dotnet-labs/ServiceWorkerCronJob

Check the existing issue.  https://github.com/dotnet-labs/ServiceWorkerCronJob/issues/14
