### ISSUE TITLE
Cronos.CronFormatException: "Unexpected character '*'."

### ISSUE THREAD

**Issue by VovaGul** [HangfireIO/Cronos#56]
expression `"0 0 4 ? * * *"` generated on [site](https://www.freeformatter.com/cron-expression-generator-quartz.html)

```
CronExpression.Parse("0 0 4 ? * * *", CronFormat.Standard) \\ Cronos.CronFormatException: "Unexpected character '*'."
```

```
CronExpression.Parse("0 0 4 ? * * *", CronFormat.IncludeSeconds) \\ Cronos.CronFormatException: "Unexpected character '*'."
```

why can't it be parsed?

Cronos 0.7.1

**Comment by VovaGul** [comment]
`0 0 4 * * *` works. 

I don't know why it works the way it does. It would be nice if something like this was taken into account or was described somewhere.

**Comment by mattheys** [comment]
It says at the top of that website that it generates Quartz cron expressions, these appear to have 7 parts.  Standard expressions have 5 and Cronos supports an options 6th for seconds.  Quartz seems to support a year variable which standard cron doesn't.

**Comment by VovaGul** [comment]
Понял. Спасибо за ответ!
