### ISSUE TITLE
Feature Request: "TryParse" or/and "IsValid" methods

### ISSUE THREAD

**Issue by Pirand92** [HangfireIO/Cronos#59]
Hi everyone,

could be possible to have one of these two methods to avoid everytime to catch the **CronFormatException**?
If you allow users to contribute on the project, I'll be enthusiast to create a PR on that.

Thanks for attention.

**Comment by odinserj** [comment]
Yeah, sure, will be happy to get this awesome PR!

**Comment by Pirand92** [comment]
> Yeah, sure, will be happy to get this awesome PR!

Thanks. Finally I found time to work on this. Unfortunately I'm facing with an issue when I try to push my branch on this repository, could be possible you have set some security policy to prevent that?

Thanks for support.

**Comment by FaithfulDev** [comment]
@Pirand92 If I understand correctly, you made a branch, committed stuff on it and now try to push that branch to this specific repository? If so, you can't do that.

You need to fork this repository (here is the[ fork link for this repo](https://github.com/HangfireIO/Cronos/fork)), this will create a "copy" of this repository in your personal namespace. There, you make any commits you need. Once you are done, create a new PR, specifying your fork branch as the source.

This is the usual way you contribute to GitHub projects. Hope that helps.

**Comment by Pirand92** [comment]
@FaithfulDev thanks a lot for your explanation. I'm used to work on Azure DevOps and there the procedure is slightly different
