### ISSUE TITLE
Minor request: Public variables for Hourly / Daily / Minutely

### ISSUE THREAD

**Issue by tspence** [HangfireIO/Cronos#64]
A small request that might be easily satisfied - can the static readonly values on `CronExpression.cs` become public rather than private?

I noticed in my code that a common usage pattern was this:

```
        var scheduledTime = _configuration["AlertsScheduledJobsWorker:ScheduledTimeExpression"]
                            ?? "0 * * * *"; // By default run once per hour
```

I noticed this happens a half dozen times in our codebase, so I decided to replace `0 * * * *` with a constant `CronExpression.Hourly`, and I decided to check if your library had one.  It looks like those values already exist, but they are marked private. Would you accept a small PR to make these values public?

**Comment by odinserj** [comment]
Thanks, done!
