### ISSUE TITLE
CronFormatException.Message has duplicated BaseMessage

### ISSUE THREAD

**Issue by jorarsus** [HangfireIO/Cronos#74]
Hello,

The Message property of CronFormatException has the base message `"The given cron expression has an invalid format."` duplicated.

For example, this piece of code

```
        try
        {
            CronExpression.Parse("61 * * * * *", CronFormat.IncludeSeconds);
        }
        catch (CronFormatException e)
        {
            var errorMessage = e.Message;
        }
```

shows the following error message: `"The given cron expression has an invalid format. The given cron expression has an invalid format. Seconds: Value must be a number between 0 and 59 (all inclusive)."`

**Comment by odinserj** [comment]
Thanks, fixed!
